// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GanaPay.Infrastructure.Data;

#nullable disable

namespace GanaPay.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218123050_AddStoredProcedures")]
    partial class AddStoredProcedures
    {
        // No necesitamos BuildTargetModel para SPs
    }
}